### PR TITLE
Fix broken basic.tex build

### PR DESCRIPTION
**Pull request by msegado**
...just a small typo (thanks to Jen French for the fix).

### CODE REVIEW

**Comment by pdpinch** [comment]
@itsbenweeks @evheubel who can merge this?

**Comment by evheubel** [comment]
@pdpinch this fix is also in another pending pull request along with numerous other modifications for the demo course to compile to XML and PDF.
https://github.com/evheubel/content-mit-latex2edx-demo/commit/4a9c37be58ae7defd095d2ab811fa9f8d13e4d96#diff-77adf2c5df3361d208d920626094083eR160

**Comment by itsbenweeks** [comment]
Thanks for pointing this out, Peter. We weren't sure who was responsible for this repository, but I'll be happy to review with @evheubel.

And thank you, @msegado for PRing this typo. PR#3 should take care of this.

**Comment by msegado** [comment]
Got it, thanks! Feel free to close.

**Pull request closed without merging**
